component hint="Generated by FuseboxFreedom http://www.github.com/jamie-pate/FuseBoxFreedom" {
//Handle all the boilerplate
	this.fb = createObject('component', 'cfcs.fbFreedom').init(this, variables)
	this.fb.access_level = "public";
	//2 : <prefuseaction />
	this.fb.acl["init"] = "";
	//fuseAction
	function init() {
		//3 : <set name="testvar" value="prefuse" />
		testvar = "prefuse";
		//4 : <set name="test_title" value="FuseBox Freedom!" />
		test_title = "FuseBox Freedom!";
	}

	//6 : <fuseaction name="test_fa" />
	this.fb.acl["test_fa"] = "";
	//fuseAction
	function test_fa() {
		//7 : <set name="testvar2" value="fuseaction" />
		testvar2 = "fuseaction";
		//8 : <set name="testvar" value="fuseaction" overwrite="false" />
		if (not isdefined("testvar")) {
			testvar = "fuseaction";
		}
		//9 : <include template="test_fa.cfm" contentvariable="test_result" />
		test_result = this.fb.include("test_fa.cfm");
		//10 : <include template="test_fa_result.cfm" />
		writeOutput(this.fb.include("test_fa_result.cfm"));
	}

}